apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "16"
  labels:
    app: saber-monitoring-service
  name: saber-monitoring-service
  namespace: default
  resourceVersion: "65918483"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: saber-monitoring-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: saber-monitoring-service
    spec:
      containers:
      - env:
        - name: WHALE_MONITOR_THRESHOLD
          value: "4000000"
        - name: NETWORK_NAME
          value: "mainnet"
        - name: RPC_URL
          valueFrom:
            secretKeyRef:
              key: MAINNET_RPC_URL2
              name: env-vars
        - name: TWITTER_APP_KEY
          valueFrom:
            secretKeyRef:
              key: SABERWARS_TWITTER_APP_KEY
              name: env-vars
        - name: TWITTER_APP_SECRET
          valueFrom:
            secretKeyRef:
              key: SABERWARS_TWITTER_APP_SECRET
              name: env-vars
        - name: TWITTER_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              key: SABERWARS_TWITTER_ACCESS_TOKEN
              name: env-vars
        - name: TWITTER_ACCESS_SECRET
          valueFrom:
            secretKeyRef:
              key: SABERWARS_TWITTER_ACCESS_SECRET
              name: env-vars
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: SABER_MESSAGING_PRIVATE_KEY
              name: env-vars
        image: dialectlab/saber-monitoring-service:0.0.1
        imagePullPolicy: Always
        name: saber-monitoring-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
